- name: variables
  hosts: localhost
  vars: #variable declaration
    Course: "Terraform"
    Trainer: "siva"
    Duration: "20hrs"
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: "Hi,I am learning {{Course}} from Trainer {{Trainer}},Duration is {{Duration}}"