- name: variables
  hosts: localhost
  vars:
    Course: "Devops"
    Trainer: "Siva"
    Duration: "120hrs"
  tasks:
  - name: print override information
    vars:
      Course: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}} from Trainer {{}},Duration is {{Duration}}"
  
    
