- name: variables from files
  hosts: localhost
  vars:
    vars_file:
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}} from Trainer {{Trainer}},Duration is {{Duration}}"

