- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
      Timings: "07:15AM IST"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}} from Trainer {{Trainer}},Duration is {{Duration}} Timings are {{Timings}}"