- name: default value
  hosts: localhost
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "hello {{Course | default('Ansible')}}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "good morning"
  tasks:
  - name: convert into upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"
    
- name: lower case
  hosts: localhost
  vars:
    greeting: "GOOD MORNING"
  tasks:
  - name: convert into lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,2,3,3,4,4,5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"

- name: print min and max 
  hosts: localhost
  vars:
    ages: [25,35,40,12,16]
  tasks:
  - name: print min and max ages
    ansible.builtin.debug:
      msg: "min age: {{ ages | min}}, max age: {{ ages | max}}"

- name: convert dictonary into items/list
  hosts: localhost
  vars:
    my_dict: #this is called map or dictionary or key value pair
      Course: Ansible
      Trainer: siva
      Duration: 8hrs
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "before convert: {{my_dict}}"
  - name: after convert
    ansible.builtin.debug:
      msg: "after convert: {{my_dict | dict2items}}"
